version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"

  product-service:
    build: ./product-service
    ports:
      - "4002:4002"

  order-service:
    build: ./order-service
    ports:
      - "4003:4003"